### PR TITLE
sp_helpme - add incl col

### LINKED ISSUE #264: [Request] sp_helpme - Add Included Columns for INDEX on TABLE
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
Within the `index_name` , `index_description`, and `index_keys` table output, I'd like to see an `index_includes` or the like column. I see from [this line](https://github.com/lowlydba/dba-multitool/blob/main/sp_helpme.sql#L424) that we are using `sp_helpindex`. I'd assume we would have to implement that output [ourselves](https://www.mssqltips.com/sqlservertip/3450/sql-server-index-report-with-included-columns-storage-and-more-for-all-tables-in-a-database/). With _2017_ support only, we could use `STRING_AGG` to comma delimit the columns. Right now, the procedure does work on 2014 and I'd rather use the[ XML trick](https://stackoverflow.com/a/17591536/14905075) for it. 

Thoughts?

**Describe alternatives you've considered**
My alternative was inspecting the index properties within _SQL Server Management Studio_.

**Additional context**
Here is the output data showing the table.
image

Can try to use `dbatools` , `Get-DbaHelpIndex` as inspiration.

### PR DESCRIPTION
**Pull request by lowlydba**
Add included columns to the standard output from sp_helpindex.

## Description

I decided to keep in place the original sp_helpindex since this is a small addition and there are some very specific ways that sp_helpindex works. With a focus on keeping the "drop in replacement" functionality I think it is better to keep the overall behavior, error reporting, etc. as original as possible/reasonable.

Unrelated:

* Remove Appveyor CI
* Enhance unit tests
* Update copyright year on all procs
* Clarify README support section
* Fix SSL issues

**Issue:** Fixes #264 

## How Has This Been Tested?

MARs are hard to test, so this was tested manually.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have updated the Version number of any scripts modified.
- [x] I have updated the documentation accordingly. - See https://github.com/lowlydba/dba-multitool.org/commit/33e6aad008c104ff9286487e21b2ab6770e0d5e5
- [x] I have read the [**CONTRIBUTING**](https://github.com/LowlyDBA/dba-multitool/blob/master/.github/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by lowlydba** [comment]
@mattcargile Can you check if the version in this branch fits your needs?

**Comment by mattcargile** [comment]
Good stuff. I kept looking at source of `sp_helpindex`. I was considering rewriting the entire thing. 

I keep returning `NULL` for `index_include`. I have been playing around with it for a little on non `dbo` schema dbs and case sensitive dbs. I seem to remember that can be something weird with `FOR XML PATH` and _CTE_s?  I'll play with it some more later.

**Comment by mattcargile** [comment]
I got somewhere but I still don't know **why** it works this way. In the `includedColumns` _CTE_, I had to declare the three-part name for `indexes` , `index_column` , etc  otherwise the _CTE_ was empty.

**Comment by lowlydba** [comment]
Oof this is quickly becoming a pain. Thanks for diving in.

I agree that dynamic seems like maybe the best route to go next, I'll give that a shot and see where it gets us.

**Comment by lowlydba** [comment]
@mattcargile How's this looking now?

**Comment by mattcargile** [comment]
It is working great. 

I had looked at it a couple days ago and left a _review_ above about the `sp_executesql` context. I didn't realize the `#sp_helpindex` would exist. I think I was thinking about the new permissions context with `sp_executesql` instead.

**Comment by lowlydba** [comment]
Great! Thanks for the feedback.

I'll try to merge and release this week.

**Pull request merged**
